"""What ``save()`` writes into the merged image data section (#866).

The section is regenerated whenever the document is marked updated, and it used
to be regenerated by rendering the composite to a PIL image and splitting that.
A PIL image describes PIL: one byte per channel whatever the header's depth
says, only the channels its mode has a letter for, a bit set the other way
round in mode ``"1"``, its own web palette in mode ``"P"``, an inverted
``"CMYK"``, and -- since the render applies the document's ICC profile -- an
sRGB copy of a document whose profile resource is still attached.

So a 16-bit document got a section half its declared length, which neither
psd-tools nor Photoshop can read back; a document with spot channels lost them;
and an 8-bit one came back with the right *shape* and the wrong pixels. The
planes are built from the compositor's arrays now, in the document's own
channels, depth and conventions, which is what these measure.
"""

import io
import logging
import warnings
from pathlib import Path
from typing import Literal

import numpy as np
import pytest
from PIL import Image

from psd_tools.api.numpy_io import (
    _encode_array,
    _fit,
    _parse_array,
    encode_image_data,
)
from psd_tools.api.psd_image import PSDImage
from psd_tools.api.utils import get_transparency_index, has_transparency
from psd_tools.compression import _row_size
from psd_tools.constants import Compression, Resource
from psd_tools.psd.image_resources import AlphaIdentifiers, ImageResource

from ..utils import full_name

pytest.importorskip("aggdraw")
pytest.importorskip("scipy")
pytest.importorskip("skimage")

from psd_tools.composite import composite  # noqa: E402

# The colour-mode matrix, the two deep fixtures the issue measured, and the
# four documents whose channel count PIL's mode could not hold.
_FIXTURES = [
    "colormodes/100x20_1bit_bitmap_rle.psd",
    "colormodes/20x5_1bit_bitmap.psd",
    "colormodes/4x4_16bit_cmyk.psd",
    "colormodes/4x4_16bit_grayscale.psd",
    "colormodes/4x4_16bit_lab.psd",
    "colormodes/4x4_16bit_multichannel.psd",
    "colormodes/4x4_16bit_rgb.psd",
    "colormodes/4x4_1bit_bitmap.psd",
    "colormodes/4x4_32bit_grayscale.psd",
    "colormodes/4x4_32bit_rgb.psd",
    "colormodes/4x4_8bit_cmyk.psd",
    "colormodes/4x4_8bit_duotone.psd",
    "colormodes/4x4_8bit_grayscale.psd",
    "colormodes/4x4_8bit_index_color.psd",
    "colormodes/4x4_8bit_lab.psd",
    "colormodes/4x4_8bit_rgb.psd",
    "colormodes/4x4_8bit_rgba.psd",
    "16bit5x5.psd",
    "32bit5x5.psd",
    "cmyk-spot.psd",
    "effects/stroke-without-vector-mask.psd",
    "layers/pixel-layer.psd",
    "transparentbg.psd",
    "transparency/fill-opacity.psd",
]

# One stored step at each depth, doubled, and for depth 8 doubled again: an
# indexed document is quantized onto its own colour table rather than rounded,
# and the nearest entry can be a step away on each axis.
_TOLERANCE = {1: 0.0, 8: 4.0 / 255.0, 16: 2.0 / 65535.0, 32: 1e-5}


def _declared_length(psd: PSDImage) -> int:
    header = psd._record.header
    return _row_size(header.width, header.depth) * header.height * header.channels


def _resaved(psd: PSDImage) -> PSDImage:
    """Mark the document updated, save it, and read it back."""
    psd.mark_updated()
    buffer = io.BytesIO()
    psd.save(buffer)
    buffer.seek(0)
    return PSDImage.open(buffer)


@pytest.mark.parametrize("filename", _FIXTURES)
def test_a_regenerated_preview_reads_back_as_what_was_composited(
    filename: str,
) -> None:
    """The section is the declared length, and it holds the render.

    Both halves are needed. The length alone passes on a document whose codec
    repairs a short body -- ``cmyk-spot.psd`` wrote four planes of seven and
    the RLE decoder filled the other three with black, so it measured the
    right size and read as an empty image. The pixels alone pass on the four
    8-bit modes that were the right shape all along.

    Colour is compared only where the stored alpha is at least half, because
    the reader divides the colour back out by it: a plane stored to within
    half a step of ``c*a + (1-a)`` comes back within ``0.5/(255*a)`` of ``c``,
    which is unbounded as the alpha falls to zero and says nothing about the
    encoding.
    """
    psd = PSDImage.open(full_name(filename))
    color, _, alpha = composite(psd)
    reopened = _resaved(psd)

    stored = reopened._record.image_data.get_data(reopened._record.header, split=False)
    assert isinstance(stored, bytes)
    assert len(stored) == _declared_length(reopened)

    array = reopened.numpy()
    planes = min(array.shape[2], color.shape[2])
    visible = np.repeat(alpha >= 0.5, planes, axis=2)
    difference = np.abs(array[:, :, :planes] - color[:, :, :planes])
    assert difference[visible].max(initial=0.0) <= _TOLERANCE[reopened.depth]


def test_the_issue_repro_reopens() -> None:
    """#866's own reproduction: one visibility edit and a 16-bit document.

    ``ValueError: Decompressed length mismatch: got 75, expected 150`` --
    75 is 5x5x3 at a byte a channel, 150 is what a depth of 16 requires.
    """
    psd = PSDImage.open(full_name("16bit5x5.psd"))
    psd[0].visible = False
    assert psd.is_updated()
    reopened = _resaved(psd)
    assert reopened.topil() is not None
    assert reopened.numpy().shape == (5, 5, 3)


@pytest.mark.parametrize("depth", [8, 16, 32])
def test_a_layerless_document_survives_a_save_at_every_depth(
    depth: Literal[8, 16, 32],
) -> None:
    """The case Photoshop rejects outright rather than rebuilding around.

    Where a document has layers Photoshop recomposites and never leans on the
    merged section, which is why a half-length one went unnoticed for so long.
    Where the merged data is all there is, it answered ``Cannot open the file
    because the open options are incorrect``. Photoshop 2026 opens the
    depth-16 file this now writes, and reads back the color it was given.

    Depth 32 additionally pins ``ImageData.new``: it packed white as the
    integer ``0xffffffff``, which is a quiet NaN read back as ``>f4``, so the
    document was NaN before it was ever saved. Photoshop still declines a
    document ``PSDImage.new(depth=32)`` builds, for a missing ``hdrt`` color
    mode data block rather than for anything in the preview (#869). What is
    asserted here is that psd-tools reads its own output and that no NaN
    reaches the file.
    """
    psd = PSDImage.new("RGB", (8, 8), color=1.0, depth=depth)
    assert not np.isnan(psd.numpy()).any()
    reopened = _resaved(psd)
    stored = reopened._record.image_data.get_data(reopened._record.header, split=False)
    assert isinstance(stored, bytes)
    assert len(stored) == _declared_length(reopened)
    assert np.array_equal(reopened.numpy(), np.ones((8, 8, 3), dtype=np.float32))


def test_a_deep_preview_carries_more_than_eight_bits() -> None:
    """Not merely the right length -- the right *values*.

    Padding the old 8-bit bytes out to the declared length would have fixed
    the section size while storing 256 distinct levels in a channel that holds
    65536. Every value would then be a multiple of 257, the widening factor;
    the render's own precision is not.
    """
    psd = PSDImage.open(full_name("16bit5x5.psd"))
    psd[0].visible = False
    reopened = _resaved(psd)
    stored = reopened._record.image_data.get_data(reopened._record.header, split=False)
    assert isinstance(stored, bytes)
    values = np.frombuffer(stored, ">u2")
    assert (values % 257 != 0).any()


@pytest.mark.parametrize(
    "filename",
    [
        "colormodes/100x20_1bit_bitmap_rle.psd",
        "colormodes/20x5_1bit_bitmap.psd",
        "colormodes/4x4_1bit_bitmap.psd",
    ],
)
def test_a_bitmap_preview_is_not_stored_as_its_own_negative(filename: str) -> None:
    """A set bit is black, and ``Image.tobytes()`` on mode ``"1"`` says white.

    These three are layerless, so the composite is a reading of the very bytes
    being rewritten and the round trip has to be the identity. It was the
    negative: every pixel inverted, which no length check can see.
    """
    psd = PSDImage.open(full_name(filename))
    before = psd.numpy()
    assert np.array_equal(_resaved(psd).numpy(), before)


def test_an_indexed_preview_is_quantized_onto_the_documents_own_palette() -> None:
    """``convert("P")`` quantizes onto PIL's web palette, not the document's.

    The colour table is still the document's after the save -- nothing
    rewrites it -- so a preview quantized against another one is read back
    through the wrong table entirely, in unrelated colours rather than merely
    coarser ones.
    """
    psd = PSDImage.open(full_name("colormodes/4x4_8bit_index_color.psd"))
    before = psd.numpy()
    reopened = _resaved(psd)
    assert reopened._record.color_mode_data.value == psd._record.color_mode_data.value
    assert np.abs(reopened.numpy() - before).max() <= 4.0 / 255.0


def test_a_profiled_cmyk_document_is_not_converted_through_srgb_and_back() -> None:
    """The preview stays in the space the attached profile describes.

    Two errors compounded here. The render applies the ICC profile, so the
    bytes stored were sRGB while the profile resource claiming to describe
    them stayed attached; and ``pil_io.post_process()`` inverts a ``CMYK``
    image, so what came out was the ink complement as well. The stored
    convention is the unsurprising one -- 255 is *no* ink, which is what
    ``numpy()`` reads as 1.0.
    """
    psd = PSDImage.open(full_name("colormodes/4x4_8bit_cmyk.psd"))
    before = psd.numpy()
    assert np.abs(_resaved(psd).numpy() - before).max() <= 2.0 / 255.0


def test_a_transparent_preview_is_stored_composited_over_white() -> None:
    """Photoshop's convention, which both readers undo and neither wrote.

    A fully transparent pixel stores white in every Photoshop-authored
    fixture that has one, and a partial one stores ``c*a + (1-a)``. Going
    through a PIL ``RGBA`` image stored the unpremultiplied colour instead,
    leaving the reader to divide out an alpha the values had never been
    multiplied by -- off by as much as 196 of 255 on this fixture.
    """
    psd = PSDImage.open(full_name("transparency/fill-opacity.psd"))
    color, _, alpha = composite(psd)
    reopened = _resaved(psd)
    planes = reopened._record.image_data.get_data(reopened._record.header)
    assert isinstance(planes, list)
    stored = np.stack(
        [
            _parse_array(p, 8, reopened.width).reshape(reopened.height, -1)
            for p in planes
        ],
        axis=2,
    )

    over_white = color * alpha + (1.0 - alpha)
    assert np.abs(stored[:, :, :3] - over_white).max() <= 1.0 / 255.0
    transparent = alpha[:, :, 0] < 0.5 / 255.0
    assert transparent.any(), "the fixture has to have a transparent pixel"
    assert (stored[:, :, :3][transparent] == 1.0).all()


@pytest.mark.parametrize(
    ("filename", "carried"),
    [
        # RGB, five channels: plane 3 is the transparency and plane 4 a spot
        # channel with nothing to regenerate it from.
        ("effects/stroke-without-vector-mask.psd", [4]),
        # CMYK, seven channels and no alpha identifiers to say which of the
        # three extra ones is transparency. None is overwritten on a guess.
        ("cmyk-spot.psd", [4, 5, 6]),
    ],
)
def test_the_channels_nothing_regenerates_are_carried_over(
    filename: str, carried: list[int]
) -> None:
    """A spot channel is not the compositor's output, so a save preserves it.

    PIL's mode had no room for these: both documents wrote four planes and the
    RLE decoder filled the rest with black on the way back in, which is how a
    section that measured the right length held an image that was not there.
    """
    psd = PSDImage.open(full_name(filename))
    before = psd._record.image_data.get_data(psd._record.header)
    assert isinstance(before, list)
    after = _resaved(psd)._record.image_data.get_data(psd._record.header)
    assert isinstance(after, list)
    for index in carried:
        assert after[index] == before[index], f"channel {index} was not carried over"
        assert any(byte for byte in after[index]), f"channel {index} came back black"


def test_an_undecodable_preview_is_not_carried_forward() -> None:
    """A failed decode must not be laundered into the file, or raised out of it.

    The codec has two ways of failing and only one of them raises: a channel
    it cannot decode is replaced with black and a warning, which no length
    check can tell from real data. Carrying that forward would write a
    plausible-looking black spot channel; letting either escape would turn
    "writes a bad preview" into "cannot save at all".
    """
    psd = PSDImage.open(full_name("effects/stroke-without-vector-mask.psd"))
    psd._record.image_data.compression = Compression.ZIP
    psd._record.image_data.data = b"\x78\x9c" + b"\xff" * 32  # garbage deflate

    with warnings.catch_warnings(record=True) as recorded:
        warnings.simplefilter("always")
        reopened = _resaved(psd)
    assert not [w for w in recorded if "channel replaced with black" in str(w.message)]

    planes = reopened._record.image_data.get_data(reopened._record.header)
    assert isinstance(planes, list)
    assert not any(planes[4]), "the unreadable spot channel was carried forward"
    assert any(planes[0]), "the color planes still came from the render"


def test_a_short_color_table_keeps_the_stored_index_plane(
    caplog: pytest.LogCaptureFixture,
) -> None:
    """An indexed document Photoshop could not have written must not abort.

    ``ColorModeData.interleave()`` reads 256 entries out of three planes with
    no bounds check, so quantizing against a truncated table is an
    ``IndexError`` rather than a poor palette. The stored plane is kept
    instead: a preview that no longer matches the layers beats a document
    that cannot be written at all.

    Exercised against the encoder rather than through ``save()``, because on
    a *layerless* indexed document the read raises first -- ``_parse_array``
    indexes the same short table to expand the stored plane -- and the corpus
    has no indexed document with layers to reach the encoder any other way.
    """
    psd = PSDImage.open(full_name("colormodes/4x4_8bit_index_color.psd"))
    color, _, alpha = composite(psd)
    before = psd._record.image_data.get_data(psd._record.header)
    assert isinstance(before, list)

    psd._record.color_mode_data.value = psd._record.color_mode_data.value[:12]
    with caplog.at_level(logging.WARNING, logger="psd_tools.api.numpy_io"):
        planes = encode_image_data(psd, color, alpha)
    assert "color table" in caplog.text
    assert planes == before, "the stored index plane was not kept"


def test_a_composite_off_the_declared_geometry_is_fitted() -> None:
    """``_fit`` crops and pads, so the section is the declared length always.

    Nothing in the corpus reaches this -- the compositor's viewport is the
    document's viewbox -- which is why it is pinned directly. A preview one
    row short or one row long is the defect this whole path exists to stop
    writing, and it must not rest on the compositor agreeing about geometry.
    """
    small = np.full((3, 2, 2), 0.25, dtype=np.float32)
    assert _fit(small, 3, 2, 1.0) is small

    grown = _fit(small, 5, 4, 1.0)
    assert grown.shape == (5, 4, 2)
    assert np.array_equal(grown[:3, :2], small)
    assert (grown[3:] == 1.0).all() and (grown[:, 2:] == 1.0).all()

    cropped = _fit(small, 2, 1, 1.0)
    assert cropped.shape == (2, 1, 2)
    assert np.array_equal(cropped, small[:2, :1])


def test_a_composite_of_the_wrong_width_is_fitted_to_the_document() -> None:
    """Too few color planes are padded, too many dropped.

    Also unreachable from the corpus, and also load-bearing: the plane count
    is what makes the section the declared length, so a render one plane
    short would otherwise write a section one plane short -- the very shape
    of the bug being fixed.
    """
    psd = PSDImage.open(full_name("colormodes/4x4_8bit_rgb.psd"))
    alpha = np.ones((4, 4, 1), dtype=np.float32)

    narrow = encode_image_data(psd, np.zeros((4, 4, 1), dtype=np.float32), alpha)
    assert len(narrow) == 3
    assert narrow[0] == b"\x00" * 16
    assert narrow[1] == b"\xff" * 16, "a missing plane is padded, not left short"

    wide = encode_image_data(psd, np.zeros((4, 4, 6), dtype=np.float32), alpha)
    assert len(wide) == 3
    assert all(len(plane) == 16 for plane in wide)


def _rgb_with_extra_channels(
    alpha_identifiers: list[int], planes: list[bytes], color: tuple[int, int, int]
) -> PSDImage:
    """A 1x1 RGB document whose extra channels are laid out as given.

    Forged rather than taken from the corpus, because the corpus cannot
    settle this: its only two RGB documents with a non-transparency fourth
    channel hold 0 or 255 there, and matting against either is the identity.
    An intermediate value is what separates a preview matted against the
    transparency from one matted against whatever sits at plane 3.
    """
    psd = PSDImage.new("RGB", (1, 1), color=0.0)
    psd.create_pixel_layer(Image.new("RGB", (1, 1), color), name="L")
    header = psd._record.header
    header.channels = len(planes)
    # A registered resource holds its *parsed* element rather than bytes, which
    # is what `ImageResources.get_data()` hands back; `ImageResource.data` is
    # annotated `bytes` and has not caught up with that.
    psd._record.image_resources[Resource.ALPHA_IDENTIFIERS] = ImageResource(
        key=Resource.ALPHA_IDENTIFIERS,
        data=AlphaIdentifiers(alpha_identifiers),  # type: ignore[arg-type]
    )
    psd._record.image_data.set_data(planes, header)
    return psd


def test_a_spot_channel_at_plane_three_does_not_matte_the_color() -> None:
    """An extra channel that is not transparency must not tint the preview.

    ``_remove_background()`` divides plane 3 out of the colour whatever the
    alpha identifiers say, and writing to match it meant an RGB document
    whose fourth channel is a spot channel had its colour matted against ink
    coverage. A layer at ``(51, 102, 153)`` over a spot plane of 128 was
    stored as ``(153, 178, 204)`` -- not a slightly wrong colour but a
    washed-out one, and written into the file rather than merely read wrong.
    """
    psd = _rgb_with_extra_channels(
        [1],  # one extra channel, identifier 1: a spot channel, not alpha
        [b"\x00", b"\x00", b"\x00", b"\x80"],
        (51, 102, 153),
    )
    assert not has_transparency(psd), "the fixture has to have no transparency"

    reopened = _resaved(psd)
    planes = reopened._record.image_data.get_data(reopened._record.header)
    assert isinstance(planes, list)
    assert [p[0] for p in planes[:3]] == [51, 102, 153]
    assert planes[3] == b"\x80", "the spot channel has to be carried over"


def test_transparency_past_plane_three_is_what_mattes_the_color() -> None:
    """And the matte follows the transparency wherever the document keeps it.

    Identifiers ``[1, 0]`` put a spot channel at plane 3 and the composite's
    transparency at plane 4. Matting by position picked the spot channel;
    matting by the identifiers picks the alpha, which is what Photoshop
    stores the preview against.

    Driven at the encoder rather than through ``save()`` on purpose. This
    layout needs a layerless document -- ``has_transparency()`` reads the
    layer count too -- and on one of those the composite is the stored
    preview read back through ``_remove_background()``, which divides plane 3
    out again. Going through the reader would measure that defect (#868)
    rather than this one.
    """
    psd = PSDImage.new("RGB", (1, 1), color=0.0)
    header = psd._record.header
    header.channels = 5
    psd._record.image_resources[Resource.ALPHA_IDENTIFIERS] = ImageResource(
        key=Resource.ALPHA_IDENTIFIERS,
        data=AlphaIdentifiers([1, 0]),  # type: ignore[arg-type,list-item]
    )
    # The spot plane is deliberately far from the alpha below: at 0x80 the two
    # mattes both round to 153 and the test proves nothing.
    psd._record.image_data.set_data(
        [b"\x00", b"\x00", b"\x00", b"\x40", b"\xcc"], header
    )
    assert has_transparency(psd)
    assert get_transparency_index(psd) == 4, "plane 4 is the transparency here"

    color = np.full((1, 1, 3), 0.2, dtype=np.float32)
    alpha = np.full((1, 1, 1), 0.5, dtype=np.float32)
    planes = encode_image_data(psd, color, alpha)

    # Matted against the alpha at plane 4: 0.2*0.5 + 0.5 = 0.6 -> 153.
    # Against the spot plane at 64/255: 0.2*0.251 + 0.749 = 0.799 -> 204.
    assert [p[0] for p in planes[:3]] == [153, 153, 153]
    assert planes[3] == b"\x40", "the spot channel has to be carried over"
    assert planes[4] == b"\x80", "plane 4 holds the composite's alpha"


@pytest.mark.parametrize("depth", [1, 8, 16, 32])
def test_encode_array_inverts_parse_array(depth: int) -> None:
    """The pair the whole path rests on, at one plane and every depth.

    Depth 1 is the one that is not merely a rescale: the value's sense is
    inverted and its row is padded to a byte boundary, so a plane whose width
    is not a multiple of eight is the case that distinguishes a working
    encoder from one that shears the image by a byte a row.
    """
    width, height = 20, 5
    rng = np.random.default_rng(866)
    plane = rng.random((height, width), dtype=np.float32)
    if depth == 1:
        plane = np.rint(plane).astype(np.float32)

    encoded = _encode_array(plane, depth, width)  # type: ignore[arg-type]
    assert len(encoded) == _row_size(width, depth) * height
    decoded = _parse_array(encoded, depth, width).reshape(height, width)  # type: ignore[arg-type]
    assert (
        np.abs(decoded - plane).max()
        <= {1: 0.0, 8: 0.5 / 255, 16: 0.5 / 65535, 32: 0.0}[depth]
    )


def test_a_built_deep_document_round_trips_through_a_file(tmp_path: Path) -> None:
    """The issue's ``new16.psd``, through the public API and a real file.

    ``create_pixel_layer()`` marks the document updated, so every deep
    document ``PSDImage.new()`` produces goes through the regenerated path on
    its first save -- which is what made this the most reachable form of the
    bug rather than a corner of it.

    The layer's *own* pixels are not asserted here because they are a
    different defect, and one this change does not touch:
    ``create_pixel_layer()`` writes a channel at one byte per pixel whatever
    the header's depth says, so at depth 16 or 32 the layer reads back empty
    and the composite is the backdrop alone. Measured on ``main``; filed
    separately.
    """
    psd = PSDImage.new("RGB", (8, 8), color=1.0, depth=16)
    psd.create_pixel_layer(Image.new("RGB", (4, 4), (255, 128, 0)), name="Layer")
    output = tmp_path / "new16.psd"
    psd.save(output)

    reopened = PSDImage.open(output)
    assert reopened.depth == 16
    assert len(reopened) == 1
    assert reopened[0].name == "Layer"
    stored = reopened._record.image_data.get_data(reopened._record.header, split=False)
    assert isinstance(stored, bytes)
    assert len(stored) == _declared_length(reopened)
    # The backdrop `new()` was given, which the regenerated preview has to
    # carry at the document's own depth rather than at PIL's.
    assert np.array_equal(reopened.numpy()[6, 6], np.ones(3, dtype=np.float32))
